#!/bin/bash
set -euo pipefail

corepack enable pnpm

node_packages=(
  cf
  @earendil-works/pi-coding-agent@latest
  @openai/codex@latest
  @anthropic-ai/claude-code@latest
  copilot-cli@latest
)

npm install -g "${node_packages[@]}"

